# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-imx6"
BBFILE_PATTERN_meta-imx6 = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-imx6 = "8"

LAYERDEPENDS_meta-imx6 = "core"
LAYERSERIES_COMPAT_meta-imx6 = "gatesgarth"
